# Site settings 配置站点
title: "HelloWorld"
home-title: A Jekyll Powered Blog With Syter Theme
description: Theme Syter
keyword: "Blog"
url: ""
baseurl: ""

defaultcover: /assets/img/profile.png

version: 0.2

# Navigation links
nav:
  home: "/"
  tags: "/page/tags"
  about: "/page/about"
  links: "/page/links"

# Footer Since
footer:
  since: 2014

# 备案号
beian: false
beianNum: 

# Author 配置博主信息
author: Your Name
nickname: Your Nickname
bio: and your description
avatar: "/assets/img/profile.png"

# Search 搜索功能
search: true

# Night mode 夜间模式
nightMode: false

# MathJax
mathjax: true

# Math Plot 绘制数学图
plot: true

# Chem Plot  绘制化学方程式
cmplot: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# theme color 主题皮肤
theme-color: "default" # default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: "circuitBoard"

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: ""
  zhihu: ""
  github: ""
  qq: ""
  twitter: ""
  bilibili: ""

# Permalink 链接格式
permalink: /blog/:title.html

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 10
paginate_path: "page:num"
exclude: [.gitignore', "README.md"]

# Compress 压缩设置
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Markdown MD解析器
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS 
RSS: true

# Plugins 插件
plugins: [jekyll-paginate]
